[Config]
MinimumVersion=27

[Distribution]
Distribution=fedora
Release=44

[Output]
Format=disk
Output=bench-terminal-minimal
OutputDirectory=output
ManifestFormat=json
CompressOutput=no

[Content]
Bootable=yes
Bootloader=systemd-boot
Autologin=no
Ssh=never
WithDocs=no
Packages=
        bash
        coreutils
        kernel-core
        systemd
        systemd-boot-unsigned
        systemd-sysusers
        systemd-udev
        util-linux-core
ExtraTrees=staging

[Validation]
Checksum=yes

[Build]
CacheDirectory=cache
Incremental=yes
History=yes

[Runtime]
VirtualMachineMonitor=qemu
Console=read-only
CPUs=2
RAM=4G
KVM=auto
VSock=yes
TPM=no
Ephemeral=yes
RuntimeNetwork=none
BindUser=no
RuntimeBuildSources=no
Register=no
